"""
ChatOps command parser for slash commands
Handles /approve, /revise, /reject commands from GitHub comments
"""
import logging
import re
from typing import Optional, Dict, Any, Tuple

logger = logging.getLogger(__name__)


class ChatOpsCommand:
    """Parsed ChatOps command from GitHub comment"""
    def __init__(self, command: str, args: str = ""):
        self.command = command
        self.args = args


def parse_command(comment_body: str) -> Optional[ChatOpsCommand]:
    """
    Parse slash command from GitHub comment
    
    Supported commands:
    - /approve - Approve the bot's draft comment
    - /reject - Delete the bot's draft comment
    - /revise "new text" - Replace draft with new text
    
    Args:
        comment_body: Full comment text from GitHub
        
    Returns:
        ChatOpsCommand if valid command found, None otherwise
    """
    if not comment_body:
        return None
    
    # Match /command at start of line (after optional whitespace)
    # /approve
    approve_match = re.match(r'^\s*/approve\s*$', comment_body, re.IGNORECASE | re.MULTILINE)
    if approve_match:
        return ChatOpsCommand("approve")
    
    # /reject
    reject_match = re.match(r'^\s*/reject\s*$', comment_body, re.IGNORECASE | re.MULTILINE)
    if reject_match:
        return ChatOpsCommand("reject")
    
    # /revise "new text here" or /revise new text here
    revise_match = re.search(
        r'^\s*/revise\s+(?:"([^"]+)"|(.+?))\s*$',
        comment_body,
        re.IGNORECASE | re.MULTILINE | re.DOTALL
    )
    if revise_match:
        # Get text from either quoted or unquoted group
        revised_text = revise_match.group(1) or revise_match.group(2)
        return ChatOpsCommand("revise", revised_text.strip())
    
    return None


def is_bot_comment(comment_author: str, bot_username: str = "github-actions[bot]") -> bool:
    """
    Check if comment is from the bot
    
    Args:
        comment_author: GitHub username of comment author
        bot_username: Expected bot username
        
    Returns:
        bool: True if comment is from bot
    """
    return comment_author.lower() == bot_username.lower()


def extract_draft_marker(comment_body: str) -> bool:
    """
    Check if comment contains draft marker
    
    Returns:
        bool: True if comment is marked as draft
    """
    # Look for common draft markers
    draft_markers = [
        "<!-- DRAFT -->",
        "🤖 **Draft Response**",
        "**[DRAFT]**"
    ]
    
    return any(marker in comment_body for marker in draft_markers)


def format_draft_comment(response: str, issue_classification: str) -> str:
    """
    Format AI response as draft GitHub comment
    
    Args:
        response: LLM-generated response text
        issue_classification: BUG/FEATURE/QUESTION
        
    Returns:
        Formatted comment with draft marker
    """
    emoji = {
        "BUG": "🐛",
        "FEATURE": "✨",
        "QUESTION": "❓"
    }.get(issue_classification, "🤖")
    
    return f"""<!-- DRAFT -->
{emoji} **Draft Response** (Generated by AI)

{response}

---
**Maintainers:** Review this response and use commands to manage it:
- `/approve` - Post this response as-is
- `/revise "your text"` - Replace with your own text
- `/reject` - Delete this draft

_This is an AI-generated draft. Human review required before approval._
"""


def format_approved_comment(response: str) -> str:
    """
    Format approved comment (removes draft markers)
    
    Args:
        response: Response text
        
    Returns:
        Clean comment without draft markers
    """
    # Remove draft markers
    clean = response.replace("<!-- DRAFT -->", "")
    clean = re.sub(r'\*\*\[DRAFT\]\*\*', '', clean)
    clean = re.sub(r'🤖 \*\*Draft Response\*\*.*?\n', '', clean, flags=re.DOTALL)
    
    # Remove instruction footer
    clean = re.sub(
        r'\n---\n\*\*Maintainers:.*?_This is an AI-generated draft.*?_',
        '',
        clean,
        flags=re.DOTALL
    )
    
    return clean.strip()
